###
POST http://127.0.0.1:8080/
Content-Type: application/json

{
  "name": "nesb01t",
  "email": "nes123456nes@163.com"
}

###
GET http://127.0.0.1:8080/
Content-Type: application/json

###
GET http://127.0.0.1:8080/user/120
Content-Type: application/json

###
DELETE http://127.0.0.1:8080/user/120
Content-Type: application/json